### ISSUE TITLE
Use `os.userInfo().shell`

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/default-shell#3]
Sometime in the future when we can target Node.js 6.

https://github.com/nodejs/node/pull/6104
## 

I have a [polyfill](https://github.com/sindresorhus/user-info), but not worth the overhead.

**Comment by yeskunall** [comment]
From the [docs](https://nodejs.org/api/os.html#os_os_userinfo_options), `os.userInfo()` always returns `null` for `shell` on Windows. In that case, do you still want to use that method from their API?

**Comment by sindresorhus** [comment]
It will only be used on non-Windows systems.

**Comment by yeskunall** [comment]
Awesome! I can make the PR using the latest API. Does this mean you're
dropping support for Node `v4`?

> --

Kunall Banerjee

**Comment by sindresorhus** [comment]
No, not yet. This is just a reminder for when I do. Node.js 4 is still LTS.
