### ISSUE TITLE
Export detect function

### ISSUE THREAD

**Issue by albinekb** [sindresorhus/default-shell#4]
We're using this module in hyper: https://github.com/zeit/hyper/blob/canary/app/session.js#L4

Since we require this module at startup, we won't see changes to the default shell, requiring a restart to use the new default shell after changing it.

I have some ideas on how to fix this, but the best might be to export the detect function too,

```js
const detect = () => {
	const env = process.env;

	if (process.platform === 'darwin') {
		return env.SHELL || '/bin/bash';
	}

	if (process.platform === 'win32') {
		return env.COMSPEC || 'cmd.exe';
	}

	return env.SHELL || '/bin/sh';
})
module.exports = detect();
module.exports.detect = detect
```

another way would be to purge the require cache in hyper, but that feels hacky.

another way is to just copy this module code into hyper/lib.

Thoughts?

**Comment by sindresorhus** [comment]
Sure, a detect method makes sense. PR welcome.
