### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by msipinski** [sindresorhus/default-shell#6]
Having a TypeScript type definition file would be nice. Without it I have to write my own type definition file or use `// @ts-ignore` above the import.

Only one short file is needed:
```TypeScript
// index.d.ts
declare module 'default-shell' {
  declare const defaultShell: string // probably could also be "let" instead of "const"
  export default defaultShell
}
```

**Comment by sindresorhus** [comment]
Sure. Pull request welcome. Follow [this styleguide](https://github.com/sindresorhus/typescript-definition-style-guide).

Some examples:
- https://github.com/sindresorhus/semver-regex/commit/039944bb5b3876913171b895488874b5c200e458
- https://github.com/sindresorhus/global-dirs/commit/0aae4d64887f77af94c4fb7ca12aa9f93c0a8291
- https://github.com/sindresorhus/md5-hex/commit/bbbfeff840f26973fbffc16d4863ae6d120079f3

**Comment by msipinski** [comment]
Hi, PR is ready
