### ISSUE TITLE
CommonJS module system support

### ISSUE THREAD

**Issue by msipinski** [sindresorhus/default-shell#9]
Hi, I know that ECMAScript Modules are the future, but for now I have a problem using ESM packages in my Electron.js project. I think that having a "hybrid" package is better!

If my understanding is correct, we can extract the code from `index.js` to a new file `index.cjs` with a CJS style `module.exports = ` and in `index.js` leave only a ESM style wrapper: `import defaultShell from './index.cjs'` and `export default defaultShell`.

**Comment by sindresorhus** [comment]
I don't plan to do a hybrid package. It comes with more problems than it solves. You can either stay on the previous version or use a bundler like Webpack.

https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
